### ISSUE TITLE
对首字母大写的单词判断不尽人意

### ISSUE THREAD

**Issue by zhengdaone** [houbb/word-checker#1]
![smw k 29l r0rspgd ya kn](https://user-images.githubusercontent.com/18456026/44296602-a9d79d00-a2f4-11e8-98db-5b8fa8982ef6.png)

**Comment by houbb** [comment]
不好意思，刚看到。
大写处理下个版本考虑是否加进去。

**Comment by houbb** [comment]
release_0.0.2 版本已解决。

详细文档：[02-单词检查引导类.md](https://github.com/houbb/word-checker/blob/master/doc/user/02-%E5%8D%95%E8%AF%8D%E6%A3%80%E6%9F%A5%E5%BC%95%E5%AF%BC%E7%B1%BB.md)

示例代码如下：

```java
  /**
     * 是否拼写正确
     * 1. 原来的单词纠正仅仅支持小写字母的检查
     * 2. 支持指定忽略大小写。
     */
    @Test
    public void isCorrectIgnoreCaseTest() {
        final String hello = "Hello";

        Assert.assertFalse(WordCheckers.word(hello).isCorrect());
        Assert.assertTrue(WordCheckers.word(hello).ignoreCase(true).isCorrect());
    }
```
