### ISSUE TITLE
是否支持自定义纠错单词数据源

### ISSUE THREAD

**Issue by HopeAndStart** [houbb/word-checker#2]
感谢大佬提供的开源工具，想问一下是否支持自定义纠正单词的数据来源

**Comment by houbb** [comment]
自定义纠正单词是指。如果我输入的单词为 wor，可以指定纠正为 word。这种纠正吗？

**Comment by houbb** [comment]
虽然没有显性支持，不过你可以覆盖这个文件即可 [src/main/resources/data/en/word.txt](https://github.com/houbb/word-checker/blob/master/src/main/resources/data/en/word.txt)

【每一行】

这个文件有多行内容，代表一个单词对应的词+词频数，逗号隔开。

例如：

```
anyway,6
```

表示 anyway 在对应的一篇文章统计中出现 6 词，次数越多，说明可能性越高。

【拓展词库】

暂时只能通过覆盖的方式，后期可以考虑添加词库的扩展功能。
即系统默认词库+用户自定义词库。

**Comment by houbb** [comment]
v0.0.4 已支持自定义词库，你可以参考下 [自定义词库](https://github.com/houbb/word-checker#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E5%BA%93)
