### ISSUE TITLE
项目很好，继续加油，有些疑问

### ISSUE THREAD

**Issue by yun-yun** [houbb/word-checker#4]
我从mysql官网爬取文档后，生成单词，然后再用这个项目对单词进行检查，然后导入单词本APP来背单词。
这里有些单词识别问题：
下图是识别失败的单词，有个别像是，upload, deployment,shark这种常见的单词，没有收录
[mysqlDicts3.0-error.txt](https://github.com/houbb/word-checker/files/4520107/mysqlDicts3.0-error.txt)

**Comment by houbb** [comment]
感谢喜爱。

原因：以前选择的词库是从文章中自己加工得到，存在单词的缺失。

允许 [自定义词库](https://github.com/houbb/word-checker#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E5%BA%93)

后续考虑借助 [ECDICT](https://github.com/skywind3000/ECDICT)，不过可能词典太大。
